### ISSUE TITLE
Provide a better link to get to WOEID

### ISSUE THREAD

**Issue by philippw** [simon04/gnome-shell-extension-weather#10]
Have a look [at this StackOverflow question](http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text%3D%22Barrie%20CA%22&format=xml).

Maybe we can integrate a form in the README that uses the second link in the approved answer (or even better limits the SELECT to woeid).

**Comment by simon04** [comment]
I support your suggestion. Currently, I'm bit short in time. So I don't know when I come to updating the README.
Feel free to submit an updated version yourself!

**Comment by philippw** [comment]
Nice link!
I'll close this issue now.
