### ISSUE TITLE
Is this extension supposed to work behind a proxy?

### ISSUE THREAD

**Issue by pridey** [simon04/gnome-shell-extension-weather#11]
Hi There,

I'm running a Fedora 15 desktop at work and so I'm stuck behind my works web proxy.  I've put the proxy settings in every place possible, both via the network settings GUI and via the gconf-editor.  I have also set the http_proxy environment variable in my bash_profile.  I can access the internet via my browser, I can install packages via yum, I can access IRC and other instant messaging services, so I'm pretty confident my proxy settings are correct and they are all in the right places.  Having done all this, I still can't get the weather extension to connect and display the weather.

I also have a laptop at home running Fedora 15 and I have built and installed this extension in the exact same way on that and it works like a charm, but I'm not stuck behind a proxy at home.  Can you tell me if your extension is supposed to work behind a proxy?  If it is supposed to could you give me some guidance on how to get it to work?  If it doesn't currently support proxies, could I please request this as a feature?

Many Thanks

**Comment by utkarshsins** [comment]
I have the same problem.
Is it anyway possible to specify a proxy setting for this extension?

**Comment by sakodak** [comment]
I have the same issue.  I'd consider this a significant issue.  If it could just use the gnome proxy settings that would be great.

**Comment by kimmotuhkanen** [comment]
Same here. As mentioned earlier "could I please request this as a feature" ;)

**Comment by simon04** [comment]
If anyone comes up with a working solution, I'm happy to integrate that. The following might helpful for developing:
- http://git.gnome.org/browse/seed-examples/tree/soup.js
- http://www.roojs.com/seed/gir-1.2-gtk-3.0/gjs/Soup.ProxyResolverDefault.html

**Comment by nocnokneo** [comment]
Simon - 

I've taken a stab at it, but with no success. Any ideas?

``` javascript
    load_json_async: function(url, fun) {
        let here = this;
        let session = new Soup.SessionAsync();
        let proxy_resolver = new Soup.ProxyResolverDefault();
        // proxy_resolver.attach(session);
        proxy_resolver.get_proxy_uri_sync(url,
                                          NULL,
                                          session.proxy_uri);
        let message = Soup.Message.new('GET', url);
        session.queue_message(message, function(session, message) {
            let jp = new Json.Parser();
            jp.load_from_data(message.response_body.data, -1);
            fun.call(here, jp.get_root().get_object());
        });
    },
```

**Comment by simon04** [comment]
nocnokneo: Unfortunately not, I experimented some time ago without success. I couldn't find any helpful documentation. Google's codesearch (http://www.google.com/codesearch#search/&q=get_proxy_uri_sync&type=cs) didn't neither

**Comment by popsas-lt** [comment]
Hope these additional lines will help.
Thanks for nice weather extension ;)

```
load_json_async: function(url, fun) {
    let here = this;
    let session = new Soup.SessionAsync();

    //added if ...
    if (Soup.Session.prototype.add_feature != null)
        Soup.Session.prototype.add_feature.call(session, new Soup.ProxyResolverDefault());
    //end

    let message = Soup.Message.new('GET', url);
    session.queue_message(message, function(session, message) {
        let jp = new Json.Parser();
        jp.load_from_data(message.response_body.data, -1);
        fun.call(here, jp.get_root().get_object());
    });
},
```

**Comment by simon04** [comment]
Please test branch `proxy`! :-)

**Comment by xtoudi** [comment]
'proxy' branch works very well !
Simple add proxy in Network (System Settings) and that's all.

**Comment by nocnokneo** [comment]
works for me!

well, mostly - I have to use the "manual" option in Gnome network proxy
configuration rather than the "automatic" option when uses a proxy
auto-config (.pac) file. at my site our .pac is full of rules that are
either difficult or impossible to replicate by using the manual proxy
server option with a bunch of host/IP exclusions. anyway, this is a problem
with many clients - clearly something to be fixed at a lower level
than gnome-shell-extension-weather!

off topic, but my $0.02 - would love an extra days worth of forecast
(today, tomorrow, and the next day). love it otherwise!

**Comment by simon04** [comment]
Apparently, there are still issues with the proxy settings, see #43. @popsas-lt, perhaps you can fix them as well. :-)

**Comment by brianjmurrell** [comment]
Since automatic proxy settings (.pac) are javascript, it should be trivial to utilize them in the JS gnome-shell framework, I would think.
