### ISSUE TITLE
Get more WOEID to work! No Buenos Aires? Crazy!

### ISSUE THREAD

**Issue by GAZ082** [simon04/gnome-shell-extension-weather#113]
Indeed. Cant use my city, Buenos Aires because it does not have a letter WOEID.

**Comment by ferdnyc** [comment]
You didn't say which Buenos Aires, but...

http://xoap.weather.com/search/search?where=buenos%20aires

``` xml
<loc id="ARBA0009" type="1">Buenos Aires, Argentina</loc>
<loc id="COXX0100" type="1">Buenos Aires, Colombia</loc>
<loc id="COXX0101" type="1">Buenos Aires, Colombia</loc>
<loc id="CSXX0023" type="1">Buenos Aires, Costa Rica</loc>
<loc id="BRXX1283" type="1">Buenos Aires, Brazil</loc>
<loc id="MXXX2780" type="1">Buenos Aires, Mexico</loc>
<loc id="ARDF0127" type="1">Aeroparque Buenos Aires, Argentina</loc>
<loc id="MXJO0669" type="1">Concepcion De Buenos Aires, Mexico</loc>
<loc id="MXPA1785" type="1">San Nicolas De Buenos Aires, Mexico</loc>
<loc id="ARBA0005" type="1">Balcarce, Argentina</loc>
```

(Yes, we need to do a better job of enabling or linking to location ID lookup services, from within the extension.)

**Comment by ferdnyc** [comment]
(Also, technically these are not WOEIDs at all. All WOEIDs are full-numeric. These are "Yahoo Location IDs". Yes, the extension currently calls them the wrong thing.)

**Comment by GAZ082** [comment]
The only and original BA, Buenos Aires, Argentina! Thanks!

**Comment by ferdnyc** [comment]
Happy to help!

If you could please Close the issue on Github... Housekeeping, yaknow. ;-)

**Comment by GAZ082** [comment]
Maid.
