### ISSUE TITLE
WEATHER_URL does not work

### ISSUE THREAD

**Issue by aelmahmoudy** [simon04/gnome-shell-extension-weather#14]
The output of: 
wget 'http://weather.yahooapis.com/forecastjson?u=c&p=48907'

is: {"code":500,"Message":"Invalid Input \/forecastjson?p=48907&amp;u=c"}

also I tried replacing p= with w= (as per the new Yahoo! Weather API documentation), and I still get an error.

**Comment by simon04** [comment]
Where did you get the id `48907` from?

The following requests work seamlessly:
- http://weather.yahooapis.com/forecastjson?p=AUXX0010
- http://weather.yahooapis.com/forecastjson?w=2295424

**Comment by aelmahmoudy** [comment]
On Tue, Sep 13, 2011 at 02:52:20AM -0700, Simon Legner wrote:

> Where did you get the id `48907` from?
> 
> The following requests work seamlessly:
> - http://weather.yahooapis.com/forecastjson?p=AUXX0010
> - http://weather.yahooapis.com/forecastjson?w=2295424
>   ---end quoted text---

Yes, you are right about the id. I tried with a good id, and it worked 
(but with the w=<id>, not  the p=<id>).

I changed the WEATHER_URL in the code to use w=, and it now works.

## 

 ‎أحمد المحمودي (Ahmed El-Mahmoudy)
  Digital design engineer
 GPG KeyID: 0xEDDDA1B7
 GPG Fingerprint: 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7
