### ISSUE TITLE
dual time

### ISSUE THREAD

**Issue by ppr1** [simon04/gnome-shell-extension-weather#15]
It's not really a issue (I don't find how post a request).

It's will be nice if we could set two differents WOEID and to watch the time for two (or more) differentes places.

**Comment by simon04** [comment]
Most easily, this could be solved with a shell script (together with cron).

See https://github.com/elad661/gnome-shell-extension-weather/commit/5d9db1db48c02882053e7fa3696c1730b49de958 for an example how this could be done.
