### ISSUE TITLE
"Extension is not compatible..."

### ISSUE THREAD

**Issue by monossido** [simon04/gnome-shell-extension-weather#16]
Hi.
I have a problem with the extension in my gnome 3 installed from gnome-unstable archlinux repository. The version is  3.1.91.

Here is the error from looking glass (lg)
"wheater@gnome-shell-extension.gnome.org" had error: extension is not compatible with current GNOME Shell and/or GJS version

**Comment by simon04** [comment]
Please try to rebuild and reinstall the extension. Afaik, the version is determined by the current version of Gnome Shell being used. Alternatively, edit `metadata.json`.

**Comment by monossido** [comment]
I edited manually metadata.json and it works, but I had also to rename the function "main" to "init". I'm not an expert but I think that it's related with this http://blog.mecheye.net/2011/08/shell-extensions-live-enable-disable/

**Comment by simon04** [comment]
There is now a separate branch `gnome3.2` which should be compatible with the development version of Gnome.
