### ISSUE TITLE
this.actor.set_child

### ISSUE THREAD

**Issue by qgadrian** [simon04/gnome-shell-extension-weather#17]
Extension gets an error: "Failed to evaluate init function:Type Error: this.actor.set_child is not a function"

I guess it's because 3.1.92 (I just updated to it now).

**Comment by eonpatapon** [comment]
Hello,

This change fixes this issue : https://github.com/eonpatapon/gnome-shell-extension-weather/commit/468d1ba9e04378ac476b382b042f3714c1deffd2

**Comment by qgadrian** [comment]
Thank you very much!
