### ISSUE TITLE
so sad this does not work under gnome shell 3.2.0

### ISSUE THREAD

**Issue by ricscabral** [simon04/gnome-shell-extension-weather#21]
i just updated to ubuntu 11.10 and this is broken:
lg gives the message that it is missing an init function. i guess according to 
https://bugs.launchpad.net/cardapio/+bug/847668
the api changed.

**Comment by simon04** [comment]
See #16: The branch `gnome3.2` provides support for Gnome 3.2

**Comment by ricscabral** [comment]
Thanks for the info! Just another note: after autogen, the configure file complains about GLIB_SETTINGS, which apparently i do not have and then the makefile has a syntax error, i'm assuming because of the previous error. I'm running ubuntu 11.10 beta and " sudo apt-get install libglib2.0-dev " solved the problem. So maybe we need a buildrequires on the configure file?

checking for XML::Parser... ok
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.22... yes
./configure: line 4194: GLIB_GSETTINGS: command not found
configure: creating ./config.status
config.status: creating Makefile
config.status: creating po/Makefile.in
config.status: creating src/Makefile
config.status: executing depfiles commands
config.status: executing po/stamp-it commands
Now type `make' to compile gnome-shell-extension-weather
rcabral@gaudi:~/Desktop/simon04-gnome-shell-extension-weather-acb1782$ make
Making all in src
make[1]: Entering directory`/home/rcabral/Desktop/simon04-gnome-shell-extension-weather-acb1782/src'
Makefile:425: **\* missing separator.  Stop.
make[1]: Leaving directory `/home/rcabral/Desktop/simon04-gnome-shell-extension-weather-acb1782/src'
make: **\* [all-recursive] Error 1

**Comment by siulcode** [comment]
@ricscabral were you able to find a solution on this issue? 

I'm getting the same "Makefile:425: **\* missing separator.  Stop." message.

**Comment by ricscabral** [comment]
I had the idea i put the solution back here for future reference.
Anyway, I remember i used this hint in
http://comments.gmane.org/gmane.linux.redhat.fedora.devel/152127
that suggested adding a build requires clause.

If you are in ubuntu, it might be a lot easier to just follow the
instructions in
http://www.techdrivein.com/2011/10/7-best-gnome-shell-extensions-install.html
and add the extensions from the repository. To activate them later on,
you will need to run gnome-tweak-tool.

Hope it helps. If not, let me know and tomorrow i can look in the
source folder to see what i changed to make it work

On Wed, Oct 26, 2011 at 17:42, siulcode
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
sudo apt-get install libglib2.0-dev
solves the problem
