### ISSUE TITLE
indicator not showing up?

### ISSUE THREAD

**Issue by ricscabral** [simon04/gnome-shell-extension-weather#22]
i installed the gnome3.2 branch and lg tells me the extension is loaded properly and the woeid has been set correctly. however, nothing shows up on the menu bar. any ideas?

rcabral@gaudi:~/Desktop/simon04-gnome-shell-extension-weather-acb1782$ gsettings get org.gnome.shell.extensions.weather woeid
'XXXX224'

**Comment by lipoja** [comment]
I'm using ArchLinux - Gnome Shell 3.2 - extension isn't showing and in lg loged an error:
Extension "weather@gnome-shell-extensions.gnome.org" had error: missing 'init' function

**Comment by sn1987a** [comment]
@lipoja: just add an empty init() function in the file extension.js:
function init(){}

**Comment by simon04** [comment]
Please reopen, if this is still relevant. The `init()` function is present in [extension.js](https://github.com/simon04/gnome-shell-extension-weather/blob/e3387159b9cb196972ba59fb981aed7e25fb54c5/src/extension.js#L713)
