### ISSUE TITLE
City, WOEID not saved using Configurator

### ISSUE THREAD

**Issue by hotice** [simon04/gnome-shell-extension-weather#23]
I know the configurator has been disabled for now, but I'm using it and wanted to let you know that the city and WOEID are not saved when changing them using the new Configurator tool. The rest of the settings work just fine.

**Comment by simon04** [comment]
I have to admit that I don't like the current config tool. IMO, the interface quite confusing (especially regarding city vs. woeid) and it should assist the user in finding the woeid. Any improvements are strongy welcome.

**Comment by aripollak** [comment]
Could you apply this fix to the gnome-3.0 branch too?
