### ISSUE TITLE
The yahoo json api may not correct for some places

### ISSUE THREAD

**Issue by tao-bioinfo** [simon04/gnome-shell-extension-weather#25]
For example, id = CHXX0099(Nanjing, China), we can just compare these two simple api: one is rss, the other is json:

http://weather.yahooapis.com/forecastjson?u=c&p=CHXX0099
http://weather.yahooapis.com/forecastrss?u=c&p=CHXX0099

They are totally different on current weather conditions! And in fact RSS is correct while json is wrong because json keeps a single temperature all the time!

I hope you can develop another branch that based on yahoo RSS weather

**Comment by indexzhuo** [comment]
I have solved this problem, modify "extension.js".

**Comment by tao-bioinfo** [comment]
Well, how do you solve the problem? How to modity "extension.js"?

**Comment by indexzhuo** [comment]
get_weather_url: function() {
        return 'http://query.yahooapis.com/v1/public/yql?format=json&q=select%20location,wind,atmosphere,units,item.condition%20from%20weather.forecast%20where%20location%3D%22' + this._woeid + '%22%20%20and%20u="' + this.unit_to_url() + '"';
    },

**Comment by tao-bioinfo** [comment]
Well, yes, this url returns correct information. However the data format is different compared to original code. When I load this modified extension, it doesn't show anything of current weather condition. Should we modify other parts of the code?

**Comment by tao-bioinfo** [comment]
In fact, if we change the get_weather_url, I think we should also change the funcition:  this.load_json_async(this.get_weather_url(), function(weather)

However I know little about javascript. Can you give me a help? You can send your extension.js to my email: billzt@hotmail.com
Thank you!

**Comment by simon04** [comment]
309c2f2 uses the code by cheukchiu. Drawback: dropped automatic conversion from all-digit-WOEID to alphanumeric WOEID.

**Comment by simon04** [comment]
Merged to `master` in 5aadd4ec56.

Please re-open on further anomalies.
