### ISSUE TITLE
weather icon code 39 seems wrong

### ISSUE THREAD

**Issue by MeisterP** [simon04/gnome-shell-extension-weather#26]
```
grep "yweather:forecast" ./forecastrss\?p=SZXX0004\&u=f 
<yweather:forecast day="Wed" date="2 Nov 2011" low="42" high="64" text="AM Showers" code="39" />
<yweather:forecast day="Thu" date="3 Nov 2011" low="45" high="63" text="Cloudy" code="26" />
```

code 39 is mapped to weather-storm but yahoo displays this: http://poncho.spahan.ch/public/pictures/wicons-yahoo.png

I think `weather-few-clouds` or `weather-showers-scattered` would be more appropriate.

**Comment by simon04** [comment]
According to http://developer.yahoo.com/weather/#codetable, code `39` means "scattered thunderstorms". Anything with a thunder in it was mapped to `weather-storm`, I think. I don't mind changing that …

**Comment by MeisterP** [comment]
You can see the icon they use here: http://weather.yahoo.com/switzerland/canton-of-basel-city/basel-city-781739/ in the "today section" of the forecast window. You can extract the code from their rss-feed.

To me it looks like their documentation is outdated.
http://developer.yahoo.com/forum/YDN-Documentation/Yahoo-Weather-API-Wrong-Condition-Code/1290534174000-1122fc3d-da6d-34a2-9fb9-d0863e6c5bc6

**Comment by simon04** [comment]
Thanks a lot!
