### ISSUE TITLE
Should determine day/night based on timezone

### ISSUE THREAD

**Issue by Wyverald** [simon04/gnome-shell-extension-weather#38]
http://i868.photobucket.com/albums/ab245/Wyverald/weather-extension.png

As you can see in the screenshot, the current local time is 14:57 (afternoon), but the current weather text says "Fair" and shows a moon. I'm in Beijing, China and using China Standard Time (GMT+08:00), and the extension should correctly show the weather to be "Sunny" or something.

I guess this is more or less API related, but for what it's worth, it seems that Yahoo! has updated its weather API to use the RSS format, maybe deprecating the JSON API?

Also, you can also see in the screenshot that the forecast is way off... The date/time panel shows that it's Thursday today while in the forecast it says today is Saturday. This bug inconsistently shows up; sometimes the forecast is good and sometimes it shifts forward in time. I'm not sure yet whether this is also linked to the API problem; if not, I can open a new bug.

**Comment by simon04** [comment]
Perhaps, this is also an effect of #25, which has been fixed recently. Please try updating and report whether this issue is gone!

**Comment by Wyverald** [comment]
Thanks, it's fixed.
