### ISSUE TITLE
Change air pressure units, possible?

### ISSUE THREAD

**Issue by usmcomm** [simon04/gnome-shell-extension-weather#39]
I am used to read the air pressure in mmHg units. Is there a way to change this on my end (by editing some files), or is this a data provided by Yahoo and is unchangeable? Thank you very much.

**Comment by simon04** [comment]
After [line 500 in extension.js](https://github.com/simon04/gnome-shell-extension-weather/blob/3158d0f4f4cdd3b8868127efeabf7dedc5c761df/src/extension.js#L500), `pressure` is set to the pressure and `pressure_unit` contains its unit. You can apply your transformation after that.

I would not like to add this as a feature (unless many request that), as I don't like mmHg (aka. Torr) and it introduces some additional complexity to the code.
