### ISSUE TITLE
Update the "prefs" branch

### ISSUE THREAD

**Issue by Odysseus86** [simon04/gnome-shell-extension-weather#40]
Could you update the <i>prefs</i> branch with the latest changes you made to the <i>master</i> branch, please? And, from now on, keep them on par?
Thanks.

**Comment by simon04** [comment]
Done in ef17385d95a3a98e664030ba2230a8d680e19f45.

I think, the `prefs` branch is ready for a merge in `master`. What do you think?

**Comment by Odysseus86** [comment]
Of course it is: not having to bother with shell commands for setting the extension is a great feature for the average user and your GUI works quite well.
