### ISSUE TITLE
Weather service should be given a location  ID, not a WOEID

### ISSUE THREAD

**Issue by richardjharris** [simon04/gnome-shell-extension-weather#41]
I set my WOEID to 12056 (Bath, UK) and the weather applet displayed weather for Duanesburg, NY.

Yahoo's weather service requires a location ID as the 'location' field, not a WOEID. For example:

http://developer.yahoo.com/yql/console/#h=select%20item%20from%20weather.forecast%20where%20location%20%3D%2012056%3B
Shows Duanesburg, NY.

It is possible to get location IDs via weather.com:
http://xoap.weather.com/search/search?where=Bath

Setting woeid to one of these IDs, e.g. UKXX0012 in my case, works as intended:

http://developer.yahoo.com/yql/console/#h=select%20item%20from%20weather.forecast%20where%20location%20%3D%20%22UKXX0012%22%3B

It seems like the applet is working for everyone else - perhaps some WOEIDs are accepted but not others?

**Comment by richardjharris** [comment]
I just noticed issue #25 which introduced this bug.
"Drawback: dropped automatic conversion from all-digit-WOEID to alphanumeric WOEID."

In that case a documentation patch would be enough :)

**Comment by ghost** [comment]
I was also having this issue, and couldn't figure out why my WOEID wasn't working.  This would be handy to have in the documentation.

**Comment by ghost** [comment]
Also the fact that in the US, one can simply use their zip code.  http://edg3.co.uk/snippets/weather-location-codes/

**Comment by mrjabba** [comment]
I had the same issue in Archlinux. The link to weather.com helped me out. All fixed now. Great contribution. Thanks!

**Comment by arifwn** [comment]
Same issue here. Thanks for the link!

**Comment by bijanbina** [comment]
also my woeid is 2251945 refer to http://weather.yahoo.com/iran/tehran/tehran-2251945 but it not work!

**Comment by simon04** [comment]
Thank you all for the links. I updated the `README` file.

bijanbina, see e.g. [here](http://xoap.weather.com/search/search?where=Tehran).

**Comment by RavanH** [comment]
FEATURE REQUEST

After installation via the WebUpD8 repositories, finding the correct location ID is a bit of a mystery and seems only possible after finding this thread where the link to xoap.weather.com is mentioned (what documentation?) ... Could this info be added to the tooltip info when hovering the WOEID field maybe? 

Or better yet, this example: type City and Country (or US zip code) in location field and the Weather Extension consults xoap.weather.com in the backround to translate it to a location id...
