### ISSUE TITLE
not using proxy

### ISSUE THREAD

**Issue by brianjmurrell** [simon04/gnome-shell-extension-weather#43]
Hi,

I'm using your weather shell extension on a machine here that is behind a proxy.  I have configured a proxy in my network preferences and logged out of the shell and back in and yet still the weather extension is trying to access the yahoo weather service directly and not via the proxy.

What is strange is that I do see mention of using a proxy resolver in the extension code:

```
        Soup.Session.prototype.add_feature.call(session, new Soup.ProxyResolverDefault());
```

I don't know why it's not using it though.

**Comment by nocnokneo** [comment]
@brianjmurrell - in the Gnome proxy configuration tool are you using the manual or automatic (.pac) for specifying your proxy? like just about every other application except the web browsers, the automatic option does not work for me.

**Comment by brianjmurrell** [comment]
I tend to try to use automatic (.pac) proxy specification since the rules for proxy use here are more complicated than the manual method allows.

**Comment by nocnokneo** [comment]
yes, I have the same problem. until Gnome proxy support improves (needs to be much more transparent to applications IMO) the only solution I've found is to switch back and forth between manual and automatic configurations (i.e. manual with no-proxy rules as best as I can get them for 95% of the time and automatic for accessing hosts that have more complex rules than just a hostname + a no-proxy hostname list). The unsolved problem is when accessing a host that needs automatic mode enabled from an application that does not support automatic mode (basically everything but web browsers)

**Comment by brianjmurrell** [comment]
Right.  But everything GNOME should be able to "just work" if GNOME properly supports automatically proxy.  That is, fix it correctly in the right place and everything else (GNOME) should just fall into line.

**Comment by simon04** [comment]
Thus, let's wait for a better proxy support in the libraries. I'll close this ticket for now.

**Comment by brianjmurrell** [comment]
Why close it?  It's an open issue, the ticket should stay open, IMHO.
