### ISSUE TITLE
Supersonic winds

### ISSUE THREAD

**Issue by Reinis** [simon04/gnome-shell-extension-weather#45]
170 8.05 km/h wind speed.. really?!
In browser it shows this:
Wind:    S 5 mph

It would be nice if it would:
- show wind direction after the speed
- show wind speed in m/s
- respect locale for decimal separator

**Comment by Reinis** [comment]
Better give wind directions as names up to half-winds
http://en.wikipedia.org/wiki/Compass_direction

E.g., N, NEN, NE, ENE, E, ...

**Comment by ghost** [comment]
I think Yahoo changed their API recently to cause this. I've written a patch to convert the degrees to one of 8 directions (N, NE, etc). I don't really think it's necessary to get as specific as NNE, ENE, etc, personally. Also, it doesn't display the direction if wind speed is 0.

[commit e88d0b42b9](https://github.com/bmars/gnome-shell-extension-weather/commit/e88d0b42b9c7bfef100b00c49e17e9e3a51c1743)

**Comment by Reinis** [comment]
Thanks! It works as expected.
Now if the units would bee something like those I see more often in weather forecasts (m/s)..
Also for the pressure usually I see Hgmm used, tough here just config option would be enough, I can live with mb.

**Comment by ghost** [comment]
Yeah, I think those would be separate feature enhancements rather than part of this bug though - Yahoo's weather API provides the units directly, and g-s-e-w just displays them. It doesn't do any conversions itself.

**Comment by simon04** [comment]
Fixed in 240cdac73405c4c13052434d273348775c5dee36.
