### ISSUE TITLE
weather-extension-configurator.py uses non-existent python2 interpreter

### ISSUE THREAD

**Issue by ghost** [simon04/gnome-shell-extension-weather#51]
On Debian, weather-extension-configurator.py returns this:

```
/usr/bin/env: python2: No such file or directory
```

Maybe it should use python2.6 or python2.7? That's probably the most compatible, since I don't think there are any systems out there that have a python2 interpreter but not python2.6/7.

**Comment by leightonearl** [comment]
Python2 would usually point to the latest python 2.*. On my machine (Fedora 16) that would be python2.7.
I am surprised that Debian does not have a python2 executable.
It could maybe be changed to python2.7 as changing it to just python would break Arch as the python executable in Arch points to python3 not 2.

What options do you have for python interpreter's? (ie what does `ls -l /usr/bin/python*` show)

**Comment by ghost** [comment]
```
$ ls -l /usr/bin/python*
lrwxrwxrwx 1 root root       9 Oct  9 05:49 /usr/bin/python -> python2.7
-rwxr-xr-x 1 root root 2634416 Aug  3 05:37 /usr/bin/python2.6
-rwxr-xr-x 1 root root    1452 Aug  3 05:34 /usr/bin/python2.6-config
-rwxr-xr-x 1 root root 2744088 Nov 30 16:41 /usr/bin/python2.7
-rwxr-xr-x 1 root root    1652 Nov 30 16:40 /usr/bin/python2.7-config
lrwxrwxrwx 1 root root      16 Oct  9 05:49 /usr/bin/python-config -> python2.7-config
```

Yeah, for whatever reason, Debian does not have a default python2 interpreter - only a default python one.

**Comment by simon04** [comment]
As there is no global scheme for naming different python versions, I suggest to patch the configurator shee-bang if needed.

**Comment by leightonearl** [comment]
#!/usr/bin/python2.7 would work globally if you make the assumption that a system running gnome3 would also have python2.7.

**Comment by simon04** [comment]
That works till `python2.8` comes out (will this ever happen?). I'm also fine with `python2.7` if this eases packaging for some distributions.

**Comment by ghost** [comment]
I think that there will [officially be no Python 2.8 release](http://www.python.org/dev/peps/pep-0404/).
