### ISSUE TITLE
Some WOEIDs not working

### ISSUE THREAD

**Issue by Odysseus86** [simon04/gnome-shell-extension-weather#52]
I signal you [this thread](https://bugzilla.rpmfusion.org/show_bug.cgi?id=2017#c6), pointing out some issues about WOEIDs. It seems that some WOEIDs don't work with your extension.
I think the problem depends on Yahoo! Weather. Anyway, if you wish, please follow the thread or take part in it.

**Comment by simon04** [comment]
Please take a look at the README (which was updated recently) under the section Configuration/Location.

**Comment by Odysseus86** [comment]
OK, I think your clarification solves the issue.
Thank you and sorry for the inconvenience.

**Comment by simon04** [comment]
You're welcome. :-)
