### ISSUE TITLE
Current master crashes gnome-shell 3.2.1 on Fedora 16 x86_64

### ISSUE THREAD

**Issue by hobbes1069** [simon04/gnome-shell-extension-weather#54]
Subject sums it up. How would I go about getting useful information on this? If I enable the extension I get the "Oh snap!" and have to log out...

**Comment by hobbes1069** [comment]
Ok, found some instructions on how to troubleshoot gnome shell. Exported the display from console, ran gnome-shell --replace, loaded the weather extension.

It worked. Go figure.

**Comment by ildar** [comment]
Well, not really.
https://bugzilla.gnome.org/show_bug.cgi?id=661323#c64
Please reopen.
