### ISSUE TITLE
woeid not being found

### ISSUE THREAD

**Issue by nobodie0** [simon04/gnome-shell-extension-weather#56]
I have tried to set up the weather extension 2 times now and in each case it fails to find anything based on my woeid. 
here is the gsettings:

org.gnome.shell.extensions.weather city 'Tampa, FL'
org.gnome.shell.extensions.weather position-in-panel 'center'
org.gnome.shell.extensions.weather refresh-interval 240
org.gnome.shell.extensions.weather show-comment-in-panel false
org.gnome.shell.extensions.weather show-text-in-panel true
org.gnome.shell.extensions.weather translate-condition false
org.gnome.shell.extensions.weather unit 'celsius'
org.gnome.shell.extensions.weather use-symbolic-icons true
org.gnome.shell.extensions.weather woeid '2503863'

I have refreshed (alt F2)
turned the extension on and off in tweak tools, , 
Installed the expected deps:

install gnome-common gtk3-devel glib2-devel intltool automake autoconf vala wget gnome-tweak-tool

and, at least in the first try, restarted and waited hours for it to find the location information
ANy other suggestions?

**Comment by simon04** [comment]
> org.gnome.shell.extensions.weather woeid '2503863'

Don't use a numeric WOEID, but one of the form ABCD1234 (see readme).

**Comment by nobodie0** [comment]
tnx, got it

On Sun, Jan 29, 2012 at 5:08 PM, Simon Legner <
reply@reply.github.com

> wrote:
> 
> > org.gnome.shell.extensions.weather woeid '2503863'
> > Don't use a numeric WOEID, but one of the form ABCD1234 (see readme).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/simon04/gnome-shell-extension-weather/issues/56#issuecomment-3711821

## 

Lofton Alley
Senior Instructor, INTO-USF
University of South Florida
Tampa, Florida, USA
