### ISSUE TITLE
Update .pot file

### ISSUE THREAD

**Issue by simon04** [simon04/gnome-shell-extension-weather#57]
The file `po/gnome-shell-extension-weather.pot` is outdated and must be updated in order to contain strings that have been added recently.

How is this done?

**Comment by mockturtl** [comment]
I used `msgmerge`.

http://oriya.sarovar.org/docs/gettext/node9.html

Hope it helps.

**Comment by dstancl** [comment]
I use
`xgettext -o gnome-shell-extension-weather.pot -L python -j --keyword=_ ../src/extension.js`
in po directory and then
`msgmerge -U cs.po gnome-shell-extension-weather.pot`
to update language file (cs.po)

**Comment by simon04** [comment]
dstancl, thanks a lot (also for the updated Czech translation). :-)
