### ISSUE TITLE
weather-extension-configurator(.py)

### ISSUE THREAD

**Issue by gracca** [simon04/gnome-shell-extension-weather#58]
There seems to be a bug when clicking in the config button, in the menu that shows the weather.

It tries to open "weather-extension-configurator" (without .py), but the installed file is called "weather-extension-configurator.py" (with .py).

Thanks,
Germán.

**Comment by simon04** [comment]
Which distribution?

**Comment by gracca** [comment]
It doesn't matter. The provided file is called "weather-extension-configurator.py", but the extension wants to open "weather-extension-configurator"... well, now thinking twice I'm not more sure if this is a bug... It just need to be packaged as weather-extension-configurator in /usr/bin and no more problems :)

**Comment by gracca** [comment]
This appeared because I was making an RPM package right now... and I packaged weather-extension-configurator.py in /usr/bin... then I installed this extension in my Fedora 16, and when I clicked the config button, this problem appeared... but now, as I said before, I just need to give the right name in /usr/bin, just that... :)

**Comment by simon04** [comment]
Right – that was the intention. :-)
I'll close this ticket for now.

**Comment by gracca** [comment]
Thanks and sorry for the noise :)
