### ISSUE TITLE
Locations in Australia do not load.

### ISSUE THREAD

**Issue by twoolie** [simon04/gnome-shell-extension-weather#59]
Trying to set my WOEID to 1099805 and failing to retrieve weather data.

Is there any reason why this would fail?

**Comment by darkxst** [comment]
Your WOEID is in the wrong format, it should look something like this

ASXX0075 (which is for Melbourne)

**Comment by twoolie** [comment]
I got my WOEID from the yahoo site (they seem to be the ones who came up with the standard[?]). where do you suggest getting WOEIDs from?

**Comment by darkxst** [comment]
yahoo seem to have two different formats for WOEID's, but only the ones starting with letters seem to work in Aus.

Try this site, http://edg3.co.uk/snippets/weather-location-codes/

**Comment by twoolie** [comment]
Once I knew the correct format, i was able to find the code in the <script> tags on the yahoo site ;)
