### ISSUE TITLE
No icon for "Mostly cloudy"

### ISSUE THREAD

**Issue by fudgeboy** [simon04/gnome-shell-extension-weather#6]
Seems to work very well! Thanks!

But whenever the weather is "Mostly cloudy", there's no icon available, and I just get the default one that looks like a picture frame with the bottom right corner folded slightly. Could this be fixed? (If you need an example, Guildford, UKXX1727, is currently "Mostly cloudy".)

Also... could the items in the main display be links to the appropriate pages on Yahoo? I'd suggest that the 'today' and 'tomorrow' items be links to the forecast for the next few days, and the 'current' item be a link to the hourly forecast.

James

**Comment by simon04** [comment]
"No icon" should be fixed in 232117f6b79e4ba81455.

I like your suggestions for links to Yahoo.

**Comment by Mystro256** [comment]
Agreed, having a link to further forecasts would be great
