### ISSUE TITLE
Gnome Shell crashes if I type "w" in the search box

### ISSUE THREAD

**Issue by brendanlong** [simon04/gnome-shell-extension-weather#67]
If I type window key (bring up overlay) then "w", GNOME Shell crashes. I've confirmed that it stops happening if I remove this extension.

It's possible this has existed for a long time, but I only recently installed a program starting with a "w".

I've never worked with GNOME Shell, so is there anything I can do to make this easier to debug (assuming it's not easy to reproduce). I was original on a version from 2012-02 and now I'm on the most recent version and the problem still exists.

I'm using Arch Linux with GNOME Shell 3.2.2.1 if that makes any difference.

**Comment by matasbbb** [comment]
Can't reproduce neither on 3.3.90, nor on 3.2.2.1 (gentoo).
Could you attach actual error after crash from ~/.xsession-errors

**Comment by brendanlong** [comment]
Here's what I get in the logs during a crash:

```
** Message: applet now removed from the notification area
** Message: applet now removed from the notification area
gnome-shell-calendar-server[6020]: Got HUP on stdin - exiting
gnome-shell-calendar-server[6020]: Got HUP on stdin - exiting
gnome-session[5905]: WARNING: Application 'gnome-shell.desktop' killed by signal
gnome-session[5905]: WARNING: Application 'gnome-shell.desktop' killed by signal
(gnome-shell:6267): folks-DEBUG: individual-aggregator.vala:310: Setting primary store IDs to defaults.
(gnome-shell:6267): folks-DEBUG: individual-aggregator.vala:310: Setting primary store IDs to defaults.
(gnome-shell:6267): folks-DEBUG: individual-aggregator.vala:338: Primary store IDs are 'eds' and 'system'.
(gnome-shell:6267): folks-DEBUG: individual-aggregator.vala:338: Primary store IDs are 'eds' and 'system'.

(gnome-shell:6267): Clutter-WARNING **: Attempting to add actor of type 'ShellGenericContainer' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.

(gnome-shell:6267): St-WARNING **: Actor of type 'ShellGenericContainer' is not a child of the StBoxLayout container

(gnome-shell:6267): Clutter-WARNING **: Attempting to add actor of type 'ShellGenericContainer' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.

(gnome-shell:6267): St-WARNING **: Actor of type 'ShellGenericContainer' is not a child of the StBoxLayout container
      JS LOG: GNOME Shell started at Fri Mar 16 2012 16:06:32 GMT-0600 (MDT)      JS LOG: GNOME Shell started at Fri Mar 16 2012 16:06:32 GMT-0600 (MDT)

** Message: applet now embedded in the notification area
** Message: applet now embedded in the notification area
```

**Comment by nasask8r** [comment]
If you are using the Nvidia driver version 295, this is a known problem:

http://bugs.sabayon.org/show_bug.cgi?id=3103

As of right now, the solution appears to be to downgrade to version 290.

**Comment by brendanlong** [comment]
Thanks for finding this.

In case anyone else has this problem, and explanation and workaround (make the recently used documents file empty and immutable) is available here:

http://www.nvnews.net/vbulletin/showthread.php?t=174049
