### ISSUE TITLE
All Info is not displayed

### ISSUE THREAD

**Issue by cartmanez** [simon04/gnome-shell-extension-weather#79]
I'm using the latest version of weather plugin (downloaded just now) and gnome-shell ver. 3.2.2.1-1
uname -a: Linux cartman 3.2.13-1-ARCH #1 SMP PREEMPT Sat Mar 24 09:10:39 CET 2012 x86_64 Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz GenuineIntel GNU/Linux

The "loading" arrows keep being shown in all places. 
~/.xsession-errors contains the following:
    JS ERROR: !!!   Exception was: Error: Argument 'data' (type utf8) may not be null
    JS ERROR: !!!     lineNumber = '0'
    JS ERROR: !!!     fileName = '"gjs_throw"'
    JS ERROR: !!!     stack = '"("Argument 'data' (type utf8) may not be null")@gjs_throw:0
([object _private_Soup_SessionAsync],[object _private_Soup_Message])@/usr/share/gnome-shell/extensions/weather@gnome-shell-extensions.gnome.org/extension.js:495
"'
    JS ERROR: !!!     message = '"Argument 'data' (type utf8) may not be null"'

last update to libsoup was on 20/10/2011 so the problem is anywhere else.

**Comment by cartmanez** [comment]
screen shot:
http://oi39.tinypic.com/99gwm1.jpg

**Comment by cartmanez** [comment]
Anyone?

**Comment by jwhonce** [comment]
I found that using my ZIP code in place of WOEID caused the weather information to be displayed.  YMMV.

**Comment by cartmanez** [comment]
Found out the root of the exception.
file extension.js, method load_json_async:

message.status_code is 3
message.response_body.data is null

My url is <a href="http://query.yahooapis.com/v1/public/yql?format=json&q=select%20link,location,wind,atmosphere,units,item.condition,item.forecast,astronomy%20from%20weather.forecast%20where%20location=%22BOXX0005%22%20and%20u=%22f%22">this</a> and I can see its response in a browser.

Any ideas?

**Comment by cartmanez** [comment]
Oh God, it was my proxy configuration. status 3 means SOUP_STATUS_CANT_RESOLVE_PROXY.
Closing this issue.
