### ISSUE TITLE
Problem with the makefile

### ISSUE THREAD

**Issue by pcabido** [simon04/gnome-shell-extension-weather#8]
This happens to me with Fedora 15 when I try to compile it.

Making all in src
make[1]: Entering directory `/home/pcabido/MyWork/gnome-shell/gnome-shell-extension-weather/src'
Makefile:426: *** missing separator.  Stop.
make[1]: Leaving directory`/home/pcabido/MyWork/gnome-shell/gnome-shell-extension-weather/src'
make: **\* [all-recursive] Error 1

**Comment by akilaw** [comment]
What I did was 
1. Add a tab in that line and then make the extension. 
2. Then manually copy the xml.in to /usr/share/glib-2.0/schemas 
3. rename it to xml 
4. replace <_whatever> to <whatever> and <_whatever> to <\whatever>
5. run "sudo glib-compile-schemas  ." in that folder.</whatever>

This comment says about installing some packages but I cannot find them http://www.webupd8.org/2011/06/skype-status-menu-integration.html#comment-221282862

**Comment by akilaw** [comment]
Found it it should be `libgnome-desktop-3-dev` for ubuntu

**Comment by cocorocara** [comment]
@akila87 thanks a lot. your comments helped me install the extension without problem. wonder why the makefile does not do this (xml installation) when running make install.

**Comment by akilaw** [comment]
you have to install  libgnome-desktop-3-dev for correct compiling.

**Comment by abhishekbh** [comment]
nice...
it's `gnome-desktop-devel` for rpm distros btw

**Comment by ionull** [comment]
thank you, @abhishekbh~~
