### ISSUE TITLE
Extension doesn't show up in extensions.gnome.org

### ISSUE THREAD

**Issue by quasipedia** [simon04/gnome-shell-extension-weather#86]
I read #70 and #50 but - even leaving the extensions non-filtered (i.e. any version of the gnome shell, not only 3.4.1) - the extension does not show up on the website:

https://extensions.gnome.org/#sort=name&page=16&shell_version=all

**Comment by simon04** [comment]
Not submitted yet. Please discuss in #50.

**Comment by quasipedia** [comment]
My bad... I mistakenly took the comment of @Mystro256 in bug #50 as if it was from one of the devs, and expected the extension to be there for 3.4 / after March.

Looking really forward to it anyhow! :)

**Comment by Mystro256** [comment]
Sorry bout that. I wrote that in haste and did not phrase that correctly to my intent at all :P
