### ISSUE TITLE
Conflict with GNOME Shell frippery

### ISSUE THREAD

**Issue by rmyorston** [simon04/gnome-shell-extension-weather#9]
gnome-shell-extension-weather doesn't work with the Application Menu extension from GNOME Shell frippery (http://intgat.tigress.co.uk/rmy/extensions/index.html).

The problem is that the Application Menu extension replaces the Activities button with an Application Menu so when gnome-shell-extension-weather tries to get the height of the Activities button it fails.

I suggest using Main.panel.actor.get_theme_node().get_height()-2 as the icon size instead of Main.panel.button.get_child().height.  This should work so long as there's a top panel, and I have no plans to write an extension that removes the top panel :-)

**Comment by simon04** [comment]
Thanks for reporting and fixing!
