### ISSUE TITLE
2 day forecast isn't showing, neither does the text in panel.

### ISSUE THREAD

**Issue by zbeefy** [simon04/gnome-shell-extension-weather#90]
So to make this quick I attach the picture. The title explains everything though. I'm using Ubuntu 12.04 with G-Shell 3.4, any ideas?

Thank you.

http://picpaste.com/pics/Screenshot_from_2012-04-26_20_19_42-psvDR9af.1335487639.png

**Comment by sunng87** [comment]
I'm running gnome 3.4 on archlinux, also suffer this defect. The log shows "Reference Error: sunrise is not defined"

**Comment by ghost** [comment]
Same for me. Gnome 3.4 on archlinux.

**Comment by yangle** [comment]
Somehow running the following 
`gsettings set org.gnome.shell.extensions.weather show-sunrise-sunset false`
brings up the 2-day forecast. Sunrise/sunset are still not shown.

Also Gnome 3.4 on Arch.

**Comment by zbeefy** [comment]
True, it did bring the forecast.

**Comment by simon04** [comment]
Fixed in d43df97d34177a0f61a67df75c7424ce63be8566 / 353ac1a600f78b3ca38a6711329b81f4b1d6f61f.
