### ISSUE TITLE
Yahoo weather links breaking

### ISSUE THREAD

**Issue by ferdnyc** [simon04/gnome-shell-extension-weather#92]
Not sure when this started happening, but I just noticed that the web link to Yahoo weather in the weather extension now leads to an error page. Looks like Yahoo may have finally retired the (deprecated) old-style weather IDs we've been using, in favor of real (all-numeric) WOEIDs.

(See #52, #87, #47, #48, others.)

**Comment by aripollak** [comment]
I looked into this a bit yesterday, and it just appears to me that Yahoo changed their Weather site layout without actually updating the APIs. For example, this doesn't contain the correct full weather link either: http://weather.yahooapis.com/forecastrss?w=12758715
But I haven't posted anything or contacted Yahoo for help.

**Comment by aripollak** [comment]
Looks like this finally got fixed at Yahoo.

**Comment by ferdnyc** [comment]
Agreed, though it leads to a different (and, IMHO, crappier) page than before. Thanks for pointing that out!
