### ISSUE TITLE
Sunset/sunrise not working in gnome 3.4

### ISSUE THREAD

**Issue by cartmanez** [simon04/gnome-shell-extension-weather#93]
I use gnome 3.4 and I have a problem with sunset/sunrise. My woeid is BOXX0005. I tried many others and there is always the same:
If 'Show sunset/sunrise' option is disabled, extension works fine. But if it's enabled, weather is not shown and keeps loading.
There is an error in my .xsession-errors

```
(gnome-shell:1013): Json-CRITICAL **: json_object_get_string_member: assertion `node != NULL' failed
      JS LOG: A ReferenceError has occured: sunrise is not defined
```

I've checked the resulting json in browser - sunrise is there, but for some reason it's not present in the astronomy js object (method refreshWeather: function(recurse) {...}). 
Seems like it's strange parsing error.

Please help.

**Comment by simon04** [comment]
Are you using the newest version? There have been some bug fixes wrt. sun{set,rise}.

**Comment by cartmanez** [comment]
Now it works. Thank you!
